### ISSUE TITLE
Spotify support

### ISSUE THREAD

**Issue by FreddyStudio** [timedotcc/dlivetv-unofficial-api#3]
Hey, I've got a feature request that you could add if you really wanted to.

Add spotify support, so for example when someone does !song, it'll tell the current song that is playing in the streamer's spotify playlist.

**Comment by timedotcc** [comment]
You can do that relatively easily yourself. I don't see the point that the DLive API should include this function.

* https://github.com/thelinmichael/spotify-web-api-node
